import { type Post, type User, CAMPUS_LOCATIONS } from "./types"

const mockUsers: User[] = [
  {
    id: "1",
    username: "aggie_music_lover",
    avatar: "/college-student-avatar-1.jpg",
    createdAt: new Date("2025-01-15"),
  },
  {
    id: "2",
    username: "davis_beats",
    avatar: "/college-student-avatar-2.jpg",
    createdAt: new Date("2025-01-20"),
  },
  {
    id: "3",
    username: "campus_vibes",
    avatar: "/college-student-avatar-3.jpg",
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "4",
    username: "study_sounds",
    avatar: "/college-student-avatar-4.jpg",
    createdAt: new Date("2025-02-10"),
  },
  {
    id: "5",
    username: "aggie_anthems",
    avatar: "/college-student-avatar-1.jpg",
    createdAt: new Date("2025-02-15"),
  },
  {
    id: "6",
    username: "quad_tunes",
    avatar: "/college-student-avatar-2.jpg",
    createdAt: new Date("2025-02-20"),
  },
]

export const mockPosts: Post[] = [
  {
    id: "1",
    userId: "1",
    user: mockUsers[0],
    song: {
      name: "Blinding Lights",
      artist: "The Weeknd",
      album: "After Hours",
      coverUrl: "/the-weeknd-after-hours-album-cover.jpg",
      spotifyUrl: "https://open.spotify.com/track/0VjIjW4GlUZAMYd2vXMi3b",
    },
    caption: "Perfect study vibes at the library tonight",
    location: CAMPUS_LOCATIONS[1], // Shields Library
    likes: 124,
    likedBy: ["2", "3", "4", "5"],
    comments: [
      {
        id: "c1",
        userId: "2",
        user: mockUsers[1],
        postId: "1",
        content: "This song is fire!",
        createdAt: new Date("2025-10-05T10:30:00"),
      },
      {
        id: "c2",
        userId: "3",
        user: mockUsers[2],
        postId: "1",
        content: "Been listening to this on repeat all week",
        createdAt: new Date("2025-10-05T11:00:00"),
      },
      {
        id: "c3",
        userId: "4",
        user: mockUsers[3],
        postId: "1",
        content: "The Weeknd never misses",
        createdAt: new Date("2025-10-05T11:30:00"),
      },
      {
        id: "c4",
        userId: "5",
        user: mockUsers[4],
        postId: "1",
        content: "Perfect for late night study sessions",
        createdAt: new Date("2025-10-05T12:00:00"),
      },
    ],
    createdAt: new Date("2025-10-05T09:15:00"),
  },
  {
    id: "2",
    userId: "2",
    user: mockUsers[1],
    song: {
      name: "Good Days",
      artist: "SZA",
      album: "Good Days",
      coverUrl: "/sza-good-days-single-cover.jpg",
      spotifyUrl: "https://open.spotify.com/track/3YRCqOhFifThpSRFJ1VWFM",
    },
    caption: "Morning coffee hits different with this track",
    location: CAMPUS_LOCATIONS[9], // CoHo
    likes: 242,
    likedBy: ["1", "3", "4", "5", "6"],
    comments: [
      {
        id: "c5",
        userId: "1",
        user: mockUsers[0],
        postId: "2",
        content: "SZA's voice is so soothing",
        createdAt: new Date("2025-10-05T09:00:00"),
      },
      {
        id: "c6",
        userId: "3",
        user: mockUsers[2],
        postId: "2",
        content: "This is my morning anthem",
        createdAt: new Date("2025-10-05T09:30:00"),
      },
      {
        id: "c7",
        userId: "4",
        user: mockUsers[3],
        postId: "2",
        content: "CoHo vibes are unmatched",
        createdAt: new Date("2025-10-05T10:00:00"),
      },
      {
        id: "c8",
        userId: "5",
        user: mockUsers[4],
        postId: "2",
        content: "Adding this to my playlist rn",
        createdAt: new Date("2025-10-05T10:30:00"),
      },
      {
        id: "c9",
        userId: "6",
        user: mockUsers[5],
        postId: "2",
        content: "Best song to start the day with",
        createdAt: new Date("2025-10-05T11:00:00"),
      },
    ],
    createdAt: new Date("2025-10-05T08:45:00"),
  },
  {
    id: "3",
    userId: "3",
    user: mockUsers[2],
    song: {
      name: "Levitating",
      artist: "Dua Lipa",
      album: "Future Nostalgia",
      coverUrl: "/dua-lipa-future-nostalgia-album-cover.jpg",
      spotifyUrl: "https://open.spotify.com/track/39LLxExYz6ewLAcYrzQQyP",
    },
    caption: "Post-workout energy at the ARC",
    location: CAMPUS_LOCATIONS[2], // ARC
    likes: 189,
    likedBy: ["1", "2", "4", "6"],
    comments: [
      {
        id: "c10",
        userId: "4",
        user: mockUsers[3],
        postId: "3",
        content: "Great workout song!",
        createdAt: new Date("2025-10-05T11:00:00"),
      },
      {
        id: "c11",
        userId: "1",
        user: mockUsers[0],
        postId: "3",
        content: "Adding this to my gym playlist",
        createdAt: new Date("2025-10-05T11:15:00"),
      },
      {
        id: "c12",
        userId: "2",
        user: mockUsers[1],
        postId: "3",
        content: "This album is pure gold",
        createdAt: new Date("2025-10-05T11:30:00"),
      },
      {
        id: "c13",
        userId: "5",
        user: mockUsers[4],
        postId: "3",
        content: "Dua Lipa always brings the energy",
        createdAt: new Date("2025-10-05T11:45:00"),
      },
      {
        id: "c14",
        userId: "6",
        user: mockUsers[5],
        postId: "3",
        content: "Perfect cardio song",
        createdAt: new Date("2025-10-05T12:00:00"),
      },
      {
        id: "c15",
        userId: "1",
        user: mockUsers[0],
        postId: "3",
        content: "Can't stop dancing to this",
        createdAt: new Date("2025-10-05T12:15:00"),
      },
    ],
    createdAt: new Date("2025-10-05T10:00:00"),
  },
  {
    id: "4",
    userId: "4",
    user: mockUsers[3],
    song: {
      name: "Sunflower",
      artist: "Post Malone, Swae Lee",
      album: "Spider-Man: Into the Spider-Verse",
      coverUrl: "/post-malone-sunflower-single-cover.jpg",
      spotifyUrl: "https://open.spotify.com/track/0RiRZpuVRbi7oqRdSMwhQY",
    },
    caption: "Chilling at the Silo between classes",
    location: CAMPUS_LOCATIONS[3], // The Silo
    likes: 156,
    likedBy: ["1", "2", "3", "5"],
    comments: [
      {
        id: "c16",
        userId: "1",
        user: mockUsers[0],
        postId: "4",
        content: "Such a chill vibe",
        createdAt: new Date("2025-10-05T08:00:00"),
      },
      {
        id: "c17",
        userId: "2",
        user: mockUsers[1],
        postId: "4",
        content: "Post Malone is a legend",
        createdAt: new Date("2025-10-05T08:30:00"),
      },
      {
        id: "c18",
        userId: "3",
        user: mockUsers[2],
        postId: "4",
        content: "Love this song so much",
        createdAt: new Date("2025-10-05T09:00:00"),
      },
    ],
    createdAt: new Date("2025-10-05T07:30:00"),
  },
  {
    id: "5",
    userId: "5",
    user: mockUsers[4],
    song: {
      name: "As It Was",
      artist: "Harry Styles",
      album: "Harry's House",
      coverUrl: "/harry-styles-harrys-house-album-cover.jpg",
      spotifyUrl: "https://open.spotify.com/track/4Dvkj6JhhA12EX05fT7y2e",
    },
    caption: "Walking through the quad on a sunny day",
    location: CAMPUS_LOCATIONS[0], // Memorial Union
    likes: 203,
    likedBy: ["1", "2", "3", "4", "6"],
    comments: [
      {
        id: "c19",
        userId: "1",
        user: mockUsers[0],
        postId: "5",
        content: "Harry Styles never disappoints",
        createdAt: new Date("2025-10-05T13:00:00"),
      },
      {
        id: "c20",
        userId: "2",
        user: mockUsers[1],
        postId: "5",
        content: "This song is so catchy",
        createdAt: new Date("2025-10-05T13:30:00"),
      },
      {
        id: "c21",
        userId: "3",
        user: mockUsers[2],
        postId: "5",
        content: "Perfect for a sunny day",
        createdAt: new Date("2025-10-05T14:00:00"),
      },
      {
        id: "c22",
        userId: "4",
        user: mockUsers[3],
        postId: "5",
        content: "Been on repeat all summer",
        createdAt: new Date("2025-10-05T14:30:00"),
      },
      {
        id: "c23",
        userId: "6",
        user: mockUsers[5],
        postId: "5",
        content: "Harry's House is such a good album",
        createdAt: new Date("2025-10-05T15:00:00"),
      },
    ],
    createdAt: new Date("2025-10-05T12:30:00"),
  },
  {
    id: "6",
    userId: "6",
    user: mockUsers[5],
    song: {
      name: "Anti-Hero",
      artist: "Taylor Swift",
      album: "Midnights",
      coverUrl: "/placeholder-s2k2i.png",
      spotifyUrl: "https://open.spotify.com/track/0V3wPSX9ygBnCm8psDIegu",
    },
    caption: "Late night study session at Shields",
    location: CAMPUS_LOCATIONS[1], // Shields Library
    likes: 178,
    likedBy: ["1", "2", "3", "5"],
    comments: [
      {
        id: "c24",
        userId: "1",
        user: mockUsers[0],
        postId: "6",
        content: "Taylor Swift is a genius",
        createdAt: new Date("2025-10-05T22:00:00"),
      },
      {
        id: "c25",
        userId: "2",
        user: mockUsers[1],
        postId: "6",
        content: "This song hits different at night",
        createdAt: new Date("2025-10-05T22:30:00"),
      },
      {
        id: "c26",
        userId: "3",
        user: mockUsers[2],
        postId: "6",
        content: "Midnights is her best album",
        createdAt: new Date("2025-10-05T23:00:00"),
      },
      {
        id: "c27",
        userId: "4",
        user: mockUsers[3],
        postId: "6",
        content: "Can't stop listening to this",
        createdAt: new Date("2025-10-05T23:30:00"),
      },
    ],
    createdAt: new Date("2025-10-05T21:45:00"),
  },
  {
    id: "7",
    userId: "1",
    user: mockUsers[0],
    song: {
      name: "Flowers",
      artist: "Miley Cyrus",
      album: "Endless Summer Vacation",
      coverUrl: "/placeholder-h4qd6.png",
      spotifyUrl: "https://open.spotify.com/track/0yLdNVWF3Srea0uzk55zFn",
    },
    caption: "Morning run around campus",
    location: CAMPUS_LOCATIONS[2], // ARC
    likes: 195,
    likedBy: ["2", "3", "4", "5", "6"],
    comments: [
      {
        id: "c28",
        userId: "2",
        user: mockUsers[1],
        postId: "7",
        content: "This song is so empowering",
        createdAt: new Date("2025-10-05T07:00:00"),
      },
      {
        id: "c29",
        userId: "3",
        user: mockUsers[2],
        postId: "7",
        content: "Miley's voice is incredible",
        createdAt: new Date("2025-10-05T07:30:00"),
      },
      {
        id: "c30",
        userId: "4",
        user: mockUsers[3],
        postId: "7",
        content: "Perfect running song",
        createdAt: new Date("2025-10-05T08:00:00"),
      },
      {
        id: "c31",
        userId: "5",
        user: mockUsers[4],
        postId: "7",
        content: "Can't get enough of this",
        createdAt: new Date("2025-10-05T08:30:00"),
      },
      {
        id: "c32",
        userId: "6",
        user: mockUsers[5],
        postId: "7",
        content: "This album is fire",
        createdAt: new Date("2025-10-05T09:00:00"),
      },
    ],
    createdAt: new Date("2025-10-05T06:30:00"),
  },
  {
    id: "8",
    userId: "2",
    user: mockUsers[1],
    song: {
      name: "Vampire",
      artist: "Olivia Rodrigo",
      album: "GUTS",
      coverUrl: "/placeholder-dnkwn.png",
      spotifyUrl: "https://open.spotify.com/track/1kuGVB7EU95pJObxwvfwKS",
    },
    caption: "Studying for midterms at Wellman",
    location: CAMPUS_LOCATIONS[8], // Wellman Hall
    likes: 167,
    likedBy: ["1", "3", "4", "6"],
    comments: [
      {
        id: "c33",
        userId: "1",
        user: mockUsers[0],
        postId: "8",
        content: "Olivia is so talented",
        createdAt: new Date("2025-10-05T14:00:00"),
      },
      {
        id: "c34",
        userId: "3",
        user: mockUsers[2],
        postId: "8",
        content: "This song gives me chills",
        createdAt: new Date("2025-10-05T14:30:00"),
      },
      {
        id: "c35",
        userId: "4",
        user: mockUsers[3],
        postId: "8",
        content: "GUTS is album of the year",
        createdAt: new Date("2025-10-05T15:00:00"),
      },
      {
        id: "c36",
        userId: "5",
        user: mockUsers[4],
        postId: "8",
        content: "Her lyrics are so relatable",
        createdAt: new Date("2025-10-05T15:30:00"),
      },
    ],
    createdAt: new Date("2025-10-05T13:45:00"),
  },
  {
    id: "9",
    userId: "3",
    user: mockUsers[2],
    song: {
      name: "Cruel Summer",
      artist: "Taylor Swift",
      album: "Lover",
      coverUrl: "/placeholder-ly88v.png",
      spotifyUrl: "https://open.spotify.com/track/1BxfuPKGuaTgP7aM0Bbdwr",
    },
    caption: "Grabbing lunch at the Silo",
    location: CAMPUS_LOCATIONS[3], // The Silo
    likes: 211,
    likedBy: ["1", "2", "4", "5", "6"],
    comments: [
      {
        id: "c37",
        userId: "1",
        user: mockUsers[0],
        postId: "9",
        content: "This song never gets old",
        createdAt: new Date("2025-10-05T12:00:00"),
      },
      {
        id: "c38",
        userId: "2",
        user: mockUsers[1],
        postId: "9",
        content: "Taylor's best song imo",
        createdAt: new Date("2025-10-05T12:30:00"),
      },
      {
        id: "c39",
        userId: "4",
        user: mockUsers[3],
        postId: "9",
        content: "The bridge is everything",
        createdAt: new Date("2025-10-05T13:00:00"),
      },
      {
        id: "c40",
        userId: "5",
        user: mockUsers[4],
        postId: "9",
        content: "Summer anthem for sure",
        createdAt: new Date("2025-10-05T13:30:00"),
      },
      {
        id: "c41",
        userId: "6",
        user: mockUsers[5],
        postId: "9",
        content: "Can't stop singing along",
        createdAt: new Date("2025-10-05T14:00:00"),
      },
    ],
    createdAt: new Date("2025-10-05T11:30:00"),
  },
  {
    id: "10",
    userId: "4",
    user: mockUsers[3],
    song: {
      name: "Paint The Town Red",
      artist: "Doja Cat",
      album: "Scarlet",
      coverUrl: "/doja-cat-scarlet-album-cover.jpg",
      spotifyUrl: "https://open.spotify.com/track/2Xr1dTzJee307rmrkt8c0g",
    },
    caption: "Pre-game vibes at Tercero",
    location: CAMPUS_LOCATIONS[4], // Tercero
    likes: 187,
    likedBy: ["1", "2", "3", "5", "6"],
    comments: [
      {
        id: "c42",
        userId: "1",
        user: mockUsers[0],
        postId: "10",
        content: "Doja Cat is unstoppable",
        createdAt: new Date("2025-10-05T19:00:00"),
      },
      {
        id: "c43",
        userId: "2",
        user: mockUsers[1],
        postId: "10",
        content: "This beat is insane",
        createdAt: new Date("2025-10-05T19:30:00"),
      },
      {
        id: "c44",
        userId: "3",
        user: mockUsers[2],
        postId: "10",
        content: "Perfect party song",
        createdAt: new Date("2025-10-05T20:00:00"),
      },
      {
        id: "c45",
        userId: "5",
        user: mockUsers[4],
        postId: "10",
        content: "Scarlet is her best work",
        createdAt: new Date("2025-10-05T20:30:00"),
      },
    ],
    createdAt: new Date("2025-10-05T18:45:00"),
  },
  {
    id: "11",
    userId: "5",
    user: mockUsers[4],
    song: {
      name: "Snooze",
      artist: "SZA",
      album: "SOS",
      coverUrl: "/placeholder-0k52e.png",
      spotifyUrl: "https://open.spotify.com/track/4iZ4pt7kvcaH6Yo8UoZ4s2",
    },
    caption: "Relaxing at CoHo after class",
    location: CAMPUS_LOCATIONS[9], // CoHo
    likes: 234,
    likedBy: ["1", "2", "3", "4", "6"],
    comments: [
      {
        id: "c46",
        userId: "1",
        user: mockUsers[0],
        postId: "11",
        content: "SZA's voice is heavenly",
        createdAt: new Date("2025-10-05T15:00:00"),
      },
      {
        id: "c47",
        userId: "2",
        user: mockUsers[1],
        postId: "11",
        content: "This song is so smooth",
        createdAt: new Date("2025-10-05T15:30:00"),
      },
      {
        id: "c48",
        userId: "3",
        user: mockUsers[2],
        postId: "11",
        content: "SOS is a masterpiece",
        createdAt: new Date("2025-10-05T16:00:00"),
      },
      {
        id: "c49",
        userId: "4",
        user: mockUsers[3],
        postId: "11",
        content: "Can't get enough of this",
        createdAt: new Date("2025-10-05T16:30:00"),
      },
      {
        id: "c50",
        userId: "6",
        user: mockUsers[5],
        postId: "11",
        content: "Perfect chill vibes",
        createdAt: new Date("2025-10-05T17:00:00"),
      },
      {
        id: "c51",
        userId: "1",
        user: mockUsers[0],
        postId: "11",
        content: "This is my comfort song",
        createdAt: new Date("2025-10-05T17:30:00"),
      },
    ],
    createdAt: new Date("2025-10-05T14:45:00"),
  },
  {
    id: "12",
    userId: "6",
    user: mockUsers[5],
    song: {
      name: "greedy",
      artist: "Tate McRae",
      album: "THINK LATER",
      coverUrl: "/placeholder-8m817.png",
      spotifyUrl: "https://open.spotify.com/track/3WOhcATHxK2SLd5ugnKkUz",
    },
    caption: "Dance break at the ARC",
    location: CAMPUS_LOCATIONS[2], // ARC
    likes: 176,
    likedBy: ["1", "2", "3", "4", "5"],
    comments: [
      {
        id: "c52",
        userId: "1",
        user: mockUsers[0],
        postId: "12",
        content: "Tate McRae is so underrated",
        createdAt: new Date("2025-10-05T16:00:00"),
      },
      {
        id: "c53",
        userId: "2",
        user: mockUsers[1],
        postId: "12",
        content: "This song makes me want to dance",
        createdAt: new Date("2025-10-05T16:30:00"),
      },
      {
        id: "c54",
        userId: "3",
        user: mockUsers[2],
        postId: "12",
        content: "THINK LATER is so good",
        createdAt: new Date("2025-10-05T17:00:00"),
      },
      {
        id: "c55",
        userId: "4",
        user: mockUsers[3],
        postId: "12",
        content: "Perfect workout energy",
        createdAt: new Date("2025-10-05T17:30:00"),
      },
    ],
    createdAt: new Date("2025-10-05T15:45:00"),
  },
  {
    id: "13",
    userId: "1",
    user: mockUsers[0],
    song: {
      name: "Stick Season",
      artist: "Noah Kahan",
      album: "Stick Season",
      coverUrl: "/noah-kahan-stick-season-album-cover.jpg",
      spotifyUrl: "https://open.spotify.com/track/0RP1kqoSPkVXsKiQNhMKzV",
    },
    caption: "Peaceful walk through campus",
    location: CAMPUS_LOCATIONS[0], // Memorial Union
    likes: 198,
    likedBy: ["2", "3", "4", "5", "6"],
    comments: [
      {
        id: "c56",
        userId: "2",
        user: mockUsers[1],
        postId: "13",
        content: "Noah Kahan's lyrics are poetry",
        createdAt: new Date("2025-10-05T10:00:00"),
      },
      {
        id: "c57",
        userId: "3",
        user: mockUsers[2],
        postId: "13",
        content: "This song hits so deep",
        createdAt: new Date("2025-10-05T10:30:00"),
      },
      {
        id: "c58",
        userId: "4",
        user: mockUsers[3],
        postId: "13",
        content: "Perfect for a reflective walk",
        createdAt: new Date("2025-10-05T11:00:00"),
      },
      {
        id: "c59",
        userId: "5",
        user: mockUsers[4],
        postId: "13",
        content: "Can't stop listening to this album",
        createdAt: new Date("2025-10-05T11:30:00"),
      },
      {
        id: "c60",
        userId: "6",
        user: mockUsers[5],
        postId: "13",
        content: "His voice is so soothing",
        createdAt: new Date("2025-10-05T12:00:00"),
      },
    ],
    createdAt: new Date("2025-10-05T09:30:00"),
  },
  {
    id: "14",
    userId: "2",
    user: mockUsers[1],
    song: {
      name: "Water",
      artist: "Tyla",
      album: "Water",
      coverUrl: "/tyla-water-single-cover.jpg",
      spotifyUrl: "https://open.spotify.com/track/4P5KoWXOxwuobLmHXLMobV",
    },
    caption: "Vibing at Segundo",
    location: CAMPUS_LOCATIONS[5], // Segundo
    likes: 165,
    likedBy: ["1", "3", "4", "5", "6"],
    comments: [
      {
        id: "c61",
        userId: "1",
        user: mockUsers[0],
        postId: "14",
        content: "This song is so catchy",
        createdAt: new Date("2025-10-05T17:00:00"),
      },
      {
        id: "c62",
        userId: "3",
        user: mockUsers[2],
        postId: "14",
        content: "Tyla is the next big thing",
        createdAt: new Date("2025-10-05T17:30:00"),
      },
      {
        id: "c63",
        userId: "4",
        user: mockUsers[3],
        postId: "14",
        content: "Can't get this out of my head",
        createdAt: new Date("2025-10-05T18:00:00"),
      },
      {
        id: "c64",
        userId: "5",
        user: mockUsers[4],
        postId: "14",
        content: "Perfect summer vibe",
        createdAt: new Date("2025-10-05T18:30:00"),
      },
    ],
    createdAt: new Date("2025-10-05T16:45:00"),
  },
  {
    id: "15",
    userId: "3",
    user: mockUsers[2],
    song: {
      name: "Calm Down",
      artist: "Rema, Selena Gomez",
      album: "Rave & Roses",
      coverUrl: "/placeholder-5ai9j.png",
      spotifyUrl: "https://open.spotify.com/track/3Wrjm47oTz2sjIgck11l5e",
    },
    caption: "Study break at Sciences Lab",
    location: CAMPUS_LOCATIONS[7], // Sciences Lab
    likes: 192,
    likedBy: ["1", "2", "4", "5", "6"],
    comments: [
      {
        id: "c65",
        userId: "1",
        user: mockUsers[0],
        postId: "15",
        content: "This collab is fire",
        createdAt: new Date("2025-10-05T14:00:00"),
      },
      {
        id: "c66",
        userId: "2",
        user: mockUsers[1],
        postId: "15",
        content: "Rema is so talented",
        createdAt: new Date("2025-10-05T14:30:00"),
      },
      {
        id: "c67",
        userId: "4",
        user: mockUsers[3],
        postId: "15",
        content: "Perfect study break song",
        createdAt: new Date("2025-10-05T15:00:00"),
      },
      {
        id: "c68",
        userId: "5",
        user: mockUsers[4],
        postId: "15",
        content: "This beat is addictive",
        createdAt: new Date("2025-10-05T15:30:00"),
      },
      {
        id: "c69",
        userId: "6",
        user: mockUsers[5],
        postId: "15",
        content: "Selena's verse is so good",
        createdAt: new Date("2025-10-05T16:00:00"),
      },
    ],
    createdAt: new Date("2025-10-05T13:30:00"),
  },
  {
    id: "16",
    userId: "4",
    user: mockUsers[3],
    song: {
      name: "Kill Bill",
      artist: "SZA",
      album: "SOS",
      coverUrl: "/placeholder-0k52e.png",
      spotifyUrl: "https://open.spotify.com/track/1Qrg8KqiBpW07V7PNxwwwL",
    },
    caption: "Late night at Shields Library",
    location: CAMPUS_LOCATIONS[1], // Shields Library
    likes: 215,
    likedBy: ["1", "2", "3", "5", "6"],
    comments: [
      {
        id: "c70",
        userId: "1",
        user: mockUsers[0],
        postId: "16",
        content: "SZA never misses",
        createdAt: new Date("2025-10-05T23:00:00"),
      },
      {
        id: "c71",
        userId: "2",
        user: mockUsers[1],
        postId: "16",
        content: "This song is a vibe",
        createdAt: new Date("2025-10-05T23:30:00"),
      },
      {
        id: "c72",
        userId: "3",
        user: mockUsers[2],
        postId: "16",
        content: "Perfect late night study song",
        createdAt: new Date("2025-10-06T00:00:00"),
      },
      {
        id: "c73",
        userId: "5",
        user: mockUsers[4],
        postId: "16",
        content: "SOS is album of the year",
        createdAt: new Date("2025-10-06T00:30:00"),
      },
      {
        id: "c74",
        userId: "6",
        user: mockUsers[5],
        postId: "16",
        content: "Can't stop playing this",
        createdAt: new Date("2025-10-06T01:00:00"),
      },
    ],
    createdAt: new Date("2025-10-05T22:30:00"),
  },
  {
    id: "17",
    userId: "5",
    user: mockUsers[4],
    song: {
      name: "Espresso",
      artist: "Sabrina Carpenter",
      album: "emails i can't send",
      coverUrl: "/placeholder-merk9.png",
      spotifyUrl: "https://open.spotify.com/track/2qSkIjg1o9h3YT9RAgYN75",
    },
    caption: "Morning energy at CoHo",
    location: CAMPUS_LOCATIONS[9], // CoHo
    likes: 188,
    likedBy: ["1", "2", "3", "4", "6"],
    comments: [
      {
        id: "c75",
        userId: "1",
        user: mockUsers[0],
        postId: "17",
        content: "Sabrina is so talented",
        createdAt: new Date("2025-10-05T08:00:00"),
      },
      {
        id: "c76",
        userId: "2",
        user: mockUsers[1],
        postId: "17",
        content: "This song is so catchy",
        createdAt: new Date("2025-10-05T08:30:00"),
      },
      {
        id: "c77",
        userId: "3",
        user: mockUsers[2],
        postId: "17",
        content: "Perfect coffee shop vibes",
        createdAt: new Date("2025-10-05T09:00:00"),
      },
      {
        id: "c78",
        userId: "4",
        user: mockUsers[3],
        postId: "17",
        content: "Can't stop singing this",
        createdAt: new Date("2025-10-05T09:30:00"),
      },
    ],
    createdAt: new Date("2025-10-05T07:45:00"),
  },
  {
    id: "18",
    userId: "6",
    user: mockUsers[5],
    song: {
      name: "Fortnight",
      artist: "Taylor Swift, Post Malone",
      album: "The Tortured Poets Department",
      coverUrl: "/placeholder-radt1.png",
      spotifyUrl: "https://open.spotify.com/track/6dODwocEuGzHAavXqTbwHv",
    },
    caption: "Rainy day at Cuarto",
    location: CAMPUS_LOCATIONS[6], // Cuarto
    likes: 201,
    likedBy: ["1", "2", "3", "4", "5"],
    comments: [
      {
        id: "c79",
        userId: "1",
        user: mockUsers[0],
        postId: "18",
        content: "This collab is everything",
        createdAt: new Date("2025-10-05T11:00:00"),
      },
      {
        id: "c80",
        userId: "2",
        user: mockUsers[1],
        postId: "18",
        content: "Taylor and Post together is magic",
        createdAt: new Date("2025-10-05T11:30:00"),
      },
      {
        id: "c81",
        userId: "3",
        user: mockUsers[2],
        postId: "18",
        content: "Perfect rainy day song",
        createdAt: new Date("2025-10-05T12:00:00"),
      },
      {
        id: "c82",
        userId: "4",
        user: mockUsers[3],
        postId: "18",
        content: "TTPD is incredible",
        createdAt: new Date("2025-10-05T12:30:00"),
      },
      {
        id: "c83",
        userId: "5",
        user: mockUsers[4],
        postId: "18",
        content: "Can't get enough of this",
        createdAt: new Date("2025-10-05T13:00:00"),
      },
    ],
    createdAt: new Date("2025-10-05T10:30:00"),
  },
]

export const getCurrentUser = (): User => mockUsers[0]
